spring.application.name=fileupload2
storage.bucket=file_upload_project1

storage.s3.endpoint=https://ltadiioxxtoqmczueqxa.storage.supabase.co/storage/v1/s3
storage.s3.region=eu-west-1

storage.s3.accessKey=b9e4f7fd45d2d15a3cf14f10c61f8e99
storage.s3.secretKey=09fb4adecfad89629ad02bd209bd2bd23ce48a003d265ded389caa79984501c9